name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - if: runner.os == 'Windows'
      uses: actions/cache@v1
      with:
        path: ~\AppData\Local\Programs\stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-
    - if: runner.os != 'Windows'
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-
    - uses: mstksg/setup-stack@v2
    - run: stack build
    - run: stack test
    - if: runner.os == 'Linux'
      run: |
        stack install hlint
        hlint .
